---
- name: Instalar um aplicativo no Windows via Ansible
  hosts: windows
  gather_facts: no
  tasks:
  
    - name: Instalar Chocolatey (se não estiver instalado)
      ansible.windows.win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        if (-Not (Test-Path "C:\ProgramData\choco")) {
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        }
      args:
        executable: powershell.exe

    - name: Instalar Google Chrome via Chocolatey
      ansible.windows.win_chocolatey:
        name: googlechrome
        state: present
      register: chrome_result

    - name: Exibir saída da instalação do Chrome
      debug:
        var: chrome_result
